### PR TITLE
Update docu for trading api timeout

### PR DESCRIPTION
**Pull request by funnel20**
Here is my PR for issue https://github.com/Chavithra/degiro-connector/issues/64

### CODE REVIEW

**Review by Chavithra — APPROVED** [review]
Did few changes.
This can be merged.
Feel free to update it further if you think it's necessary.

**Comment by funnel20** [comment]
The extra subsection looks good.
I only don't know why you did remove the disclaimer about increasing the timeout.
It's good to warn users why they should or should not do things.
Without the disclaimer, every user would change the timeout to a large number, and _assume_ they have managed the timeout issue. But assumptions are the mother of all ... you know.

**Comment by Chavithra** [comment]
Currently in the documentation the only timeout mentioned is the : `API timeout`

The `internal timeout` functioning is not detailed.

The outcome is the same :
- they will have to handle an exception : `ConnectionError` or `TimeoutError`
- or they will have to refresh the connection regularly 

In this PR we explain about how to change this `internal timeout`.

Which add a problematic, users putting :
- `internal timeout` > `API timeout

I don't think that would be a frequent or blocking issue.

An alternative to disclaimer I would prefer :
- explaining the differences between each timeout (internal/API)
- explaining the limit of each timeout

**Comment by funnel20** [comment]
I'm confused. The PR I wrote is for the timeout of the TraderApi. 
I don't know which internal timeout you're referring to.

**Comment by Chavithra** [comment]
This can be merged whenever you think it's ready.

**Comment by funnel20** [comment]
Please merge the existing PR, it's already way better than before.

**Comment by Chavithra** [comment]
Just out of curiosity : did you had access to the `Merge pull request` ​button ?

I though you could merge it without me, after approval.

**Comment by funnel20** [comment]
Probably it did. But wasn't aware that I would have had the option, so probably missed it. Next time I'll pay attention.

**Pull request merged**
